spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=teste;charset=iso_1
    username: sa
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create-drop


info:
  app:
    name: @project.name@
    description: @project.description@
  build:
    version: @project.version@